---
title: "Data Manipulation"
author: "Maya Spaur"
date: "9/17/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

```

# Load in a dataset
```{r}
##reads in a dataset using absolute path or relative path (always use a relative path!)

litters_data = read_csv(file = "./data_import_examples/FAS_litters.csv")

pups_data = read_csv(file = "./data_import_examples/FAS_pups.csv")

litters_data

pups_data

litters_data = janitor::clean_names(litters_data)

pups_data = janitor::clean_names(pups_data)



```

# Selecting

Select data frame, and then the columns you want.
```{r}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight)

select(litters_data, group, litter_number, starts_with("pups"))

select(litters_data, litter_number, group, everything())

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)
   

```

##Filtering
```{r}
filter(litters_data, group =='Mod8')
filter(litters_data, gd_of_birth ==20)
filter(litters_data, gd_of_birth < 20)
filter(litters_data, gd_of_birth >= 20)
filter(litters_data, gd_of_birth < 6)

drop_na(litters_data)

drop_na(litters_data, gd0_weight)

```

##Mutating
```{r}
view(mutate(litters_data, wt_gain = gd18_weight - gd0_weight))

mutate(
  litters_data,
  wt_gain = gd18_weight - gd0_weight, 
  group = str_to_lower(group)
)
```

##Arranging
```{r}
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

arrange(litters_data, pups_born_alive, gd0_weight)

```

Create a collection of commands
```{r}
litters_data = 
  read_csv(file = "./data_import_examples/FAS_litters.csv") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(gd0_weight)

litters_data
```
